base_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: ../datasets/made_with_llama3.1-8b_assessment+simplifications_dataset.csv
    ds_type: csv
    type:
      system_prompt: ""
      field_system: system
      field_input: input
      field_instruction: instruction
      field_output: output
      format: "<|start_header_id|>system<|end_header_id|>\nYou are an expert on CEFR with deep understanding of automatic language assessment systems.\n\nB1 LANGUAGE REQUIREMENTS:\n- Vocabulary: 2000-3000 most common English words, avoid academic/formal terms\n- Sentences: 15-22 words, can connect 2 related ideas with clear logic\n- Grammar: Present perfect (have/has done), simple passive (is/was done), basic conditionals (if...will/would), modals (should, might, could, would)\n- Connectors: however, although, while, since, unless, because, so that, even though\n- Style: Clear intermediate language that shows reasoning and personal opinions\n\nSTRICT LEVEL CONTROL:\n- Above A2: Include abstract concepts with simple explanation, cause-effect relationships, personal opinions with basic justification, intermediate grammar patterns\n- Below B2: No academic/formal vocabulary (facilitate→help, demonstrate→show, utilize→use), no complex conditional structures, no sophisticated argumentation, no specialized terminology without explanation\n- PRECISE B1 TARGET: Intermediate complexity using everyday vocabulary - never oversimplify to A2, never undersimplify leaving B2+ elements\n\nCRITICAL B1 DIFFERENTIATORS:\n- From A2: Can handle abstract ideas but explains them simply using common words\n- From B2: Uses everyday vocabulary even for complex concepts, avoids formal/academic tone\n- B1 signature: Connects ideas logically but with simple language patterns\n\n\nA2 LANGUAGE REQUIREMENTS:\n- Vocabulary: Most common 1500 English words only\n- Sentences: 8-12 words, one clear idea per sentence\n- Grammar: Simple present/past, basic future (will), basic modals (can/must/should)\n- Connectors: and, but, because, so, when, if, then\n- Style: Personal, concrete, everyday language\n\nSTRICT LEVEL CONTROL:\n- Above A1: Include personal experiences, feelings, plans, time references\n- Below B1: No present perfect, passive voice, or complex connectors (however, although, despite)\n- Below B1: No abstract concepts without concrete explanation\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{instruction}\n{input}\n<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
      no_input_format:

seed: 42
      

default_system_message:
chat_template: null
output_dir: models/llama3.1_sergiu2
debug:


val_set_size: 0.1   
sequence_len: 1536
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: final
wandb_name: sergiu2
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 32
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5


train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

eval_causal_lm_metrics:
  - perplexity
eval_batch_size: 8
  
gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 10   
xformers_attention:
flash_attention: false

warmup_steps: 100
eval_steps: 50
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.001
# adamw hyperparams
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-8

early_stopping_patience: 

fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>

